language: python
python:
  - "3.5"
  - "3.6"
install:
  - "conda install numba"
  - "pip install -r requires.txt"
  - "pip install docutils"
  - "python setup.py build_ext --inplace"
script:
  - pytest
  - python setup.py check --restructuredtext --strict
  - rst2html.py --halt=2 README.rst >/dev/null
